export type PostCategory = "actionopolis" | "comics" | "komikwerks";

export type Post = {
  slug: string;
  title: string;
  subtitle: string;
  date: string;
  formats: string[];
  purchaseUrl: string;
  buttonLabel: string;
  image: string;
  width: number;
  height: number;
  paragraphs: string[];
  excerpt: string;
  relatedHeading: string;
  category: PostCategory;
  ogTitle: string;
  ogDescription: string;
};

export const posts: Post[] = [
  {
    slug: "evolver",
    title: "Evolver",
    subtitle: "Book 3: Acceleration",
    date: "December 29, 2016",
    formats: ["Paperback"],
    purchaseUrl: "https://www.amazon.com/Evolver-Acceleration-3-Jason-Arnett/dp/1933925558/ref=sr_1_15?dchild=1&keywords=evolver+denton&qid=1596391111&sr=8-15",
    buttonLabel: "Purchase on Amazon",
    image: "redbear-books_0007_Evolver-Exceleraation.jpg",
    width: 563,
    height: 900,
    paragraphs: [
      "Jackson Savage can transform at will into powerful animalistic super-creatures but now his powers are malfunctioning just as he faces his greatest challenge! Jackson’s greatest enemy, Thorn, has new powers and he’s coming with an army of mutates to take the secret serum contained in Jackson. Fortunately the mysterious, secret organization OCTAVE offers to help Jackson stop Thorn’s plans for world domination but with Jackson’s abilities malfunctioning, can he save himself much less the world from Thorn’s latest attacks?",
      "Length: 110 pages",
      "Author: Jason Arnett, Phil Hestor, Jon S Lewis and Shanon Eric Denton",
    ],
    excerpt: "Jackson Savage can transform at will into powerful animalistic super-creatures but now his powers are malfunctioning just as ...",
    relatedHeading: "More Title from Actionopolis and Redbear",
    category: "actionopolis",
    ogTitle: "Evolver - Redbear Publishing",
    ogDescription: "Book 3: Acceleration",
  },
  {
    slug: "dragonblood-the-awakening",
    title: "Dragonblood: The Awakening",
    subtitle: "A hero the world needs!",
    date: "November 29, 2016",
    formats: ["Kindle", "Paperback"],
    purchaseUrl: "https://www.amazon.com/Dragonblood-Awakening-Christopher-Long/dp/1933925523/ref=sr_1_1?dchild=1&keywords=dragonblood+christopher+e+long&qid=1596159362&sr=8-1&pldnSite=1",
    buttonLabel: "Purchase on Amazon",
    image: "redbear-books_0005_Dragonblood.jpg",
    width: 563,
    height: 900,
    paragraphs: [
      "A young man is tattooed with the ancient blood of the world’s last dragon and must embrace the power coursing through him if he is to have any hope of defeating an ancient evil intent on destroying us all. Tim Lee considered himself an average teenager, until a mysterious man named Sifu and his beautiful teenage daughter, Mi Chang, came along. They showed Tim that he has amazing powers of swift speed and enhanced strength – powers that he is destined to use while saving mankind from the Seven Demons; ancient spirits that serve the ultimate evil, the Infinite Darkness. Despite his newfound super-human powers, Tim worries that he may not be strong enough to stop the Infinite Darkness from enslaving the planet. In an ultimate showdown of good versus evil, the young man must become the hero the world needs!",
      "Length: 130 pages",
      "Author: Christopher E. Long, Jim Keefe and Shannon Eric Denton",
    ],
    excerpt: "A young man is tattooed with the ancient blood of the world’s last dragon and must embrace the power coursing through him i ...",
    relatedHeading: "More Title from Actionopolis and Redbear",
    category: "actionopolis",
    ogTitle: "Dragonblood: The Awakening - Redbear Publishing",
    ogDescription: "A hero the world needs!",
  },
  {
    slug: "evolver-2-cell-structure",
    title: "Evolver: Cell Structure",
    subtitle: "Book 2 of the series.",
    date: "April 30, 2015",
    formats: ["Paperback"],
    purchaseUrl: "https://www.amazon.com/Evolver-Cell-Structure-Jason-Arnett/dp/193392571X/ref=sr_1_3?dchild=1&keywords=evolver+cell+structure+Jason+Arnett&qid=1596205835&sr=8-3",
    buttonLabel: "Purchase on Amazon",
    image: "redbear-books_0009_Evolver_2_Cell-Structure.jpg",
    width: 563,
    height: 900,
    paragraphs: [
      "Prey becomes predator when Jackson Savage rushes to save his friend from the clutches of a mad scientist determined to rule the world. His father’s experimental DNA is changing him and every time Jackson evolves he becomes less human. Working with the secret organization, OCTAVE, he is engaging in combat with mutant monsters but each conflict risks him losing control of his own body. Will he be able to stop an army of monsters without losing his humanity?",
      "Length: 124 pages",
      "Author: Jason Arnett with Shannon Eric Denton, Phil Hester and Jon S. Lewis",
    ],
    excerpt: "Prey becomes predator when Jackson Savage rushes to save his friend from the clutches of a mad scientist determined to rule t ...",
    relatedHeading: "More Title from Actionopolis and Redbear",
    category: "actionopolis",
    ogTitle: "Evolver: Cell Structure - Redbear Publishing",
    ogDescription: "Book 2 of the series.",
  },
  {
    slug: "battery",
    title: "Battery",
    subtitle: "The Arrival",
    date: "March 25, 2014",
    formats: ["Paperback"],
    purchaseUrl: "https://www.amazon.com/Battery-Arrival-Marc-Mason/dp/1933925671/ref=sr_1_1?dchild=1&keywords=Battery+the+Arrival+Denton&qid=1596391319&sr=8-1",
    buttonLabel: "Purchase on Amazon",
    image: "redbear-books_battery.jpg",
    width: 563,
    height: 900,
    paragraphs: [
      "A young Hopi girl bonds with an alien rebel to stop the Earth from being invaded. Kaia Little was unhappy to leave her Hopi heritage behind and move to the big city, and unfortunately, all of her fears have come true: she’s been relentlessly bullied, and has made only one friend, a deaf boy named Danny. Designate 5309 is an alien rebel on a world far across the universe who is on the run from bounty hunters who want to send him off to oblivion. But when a freak accident occurs at a radio telescope and allows 5309 to cross over into our world, both of these “misfits” are forced to find their courage, as their bodies are bonded together and forced into battle against a race of terrifying alien warriors. It’s a race against time to save the world, with only Kaia, Danny, and 5309 standing in the way of a full invasion!",
      "Length: 128 pages",
      "Author: Marc Meson with Shannon Eric Denton",
    ],
    excerpt: "A young Hopi girl bonds with an alien rebel to stop the Earth from being invaded. Kaia Little was unhappy to leave her Hopi h ...",
    relatedHeading: "More Title from Actionopolis and Redbear",
    category: "actionopolis",
    ogTitle: "Battery - Redbear Publishing",
    ogDescription: "The Arrival",
  },
  {
    slug: "gargantuan-rise-of-the-behemoths",
    title: "Gargantuan: Rise of the Behemoths",
    subtitle: "About the Author: Jake Bell is the creator of The Amazing Adventures of Nate Banks and the writer of Model Student and Megamatrix. He also was a plumber for a while, but he wasn’t very good at it",
    date: "January 5, 2014",
    formats: ["Paperback"],
    purchaseUrl: "https://www.amazon.com/Gargantuan-Rise-Behemoths-Jake-Bell/dp/1933925647/ref=sr_1_1?dchild=1&keywords=Jake+Bell+GArgantuan&qid=1596206844&sr=8-1",
    buttonLabel: "Purchase on Amazon",
    image: "redbear-books_0010_Gargantuan.jpg",
    width: 563,
    height: 900,
    paragraphs: [
      "Giant monsters walk the Earth again and a Rapid Response team is assembled to keep them from destroying us all! Somewhere beneath your feet, they're sleeping. If you're lucky, you'll never see a HUSL--a Humongous Unknown Subterranean Lifeform--but if you do, try not to get eaten or crushed before the HUSL - Rapid Response team gets there. Being bitten by a HUSL is deadly toxic but for the select few who survive the experience the bite endows them with superhuman endurance. The government is training the survivors in the hopes that they can combat this gargantuan menace to humanity and prevent the end of life as we know it.",
      "Length: 144 pages",
      "Author: Jake Bell with Shannon Eric Denton",
    ],
    excerpt: "Giant monsters walk the Earth again and a Rapid Response team is assembled to keep them from destroying us all! Somewhere ben ...",
    relatedHeading: "More Title from Actionopolis and Redbear",
    category: "actionopolis",
    ogTitle: "Gargantuan: Rise of the Behemoths - Redbear Publishing",
    ogDescription: "About the Author: Jake Bell is the creator of The Amazing Adventures of Nate Banks and the writer of Model Student and Megamatrix. He also was a plumber for a while, but he wasn’t very good at it",
  },
  {
    slug: "road-rager",
    title: "Road Rager",
    subtitle: "Dark Drivers",
    date: "December 28, 2013",
    formats: ["Paperback"],
    purchaseUrl: "https://www.amazon.com/Road-Rager-Eric-M-Esquivel/dp/1933925612/ref=sr_1_1?dchild=1&keywords=road+rager+Dark+drivers&qid=1596210868&s=books&sr=1-1",
    buttonLabel: "Purchase on Amazon",
    image: "redbear-books_0018_Road_Rager.jpg",
    width: 563,
    height: 900,
    paragraphs: [
      "Flynn Friedrich was built for speed. He has never met a race he couldn't win. But there's one thing he isn't fast enough to outrun...his destiny. Flynn is the latest host of \"The Road Rager\", an immortal, monstrously powerful supernatural entity made entirely of momentum and fueled by the will of the greatest racers who ever lived. Nipping at his heels are a gang of evil bikers, \"The Dark Drivers\", who will stop at nothing--including using the darkest black magick--to take that power for themselves and use it to conquer the world. Does Flynn have what it takes to kick these evildoers to the curb? It's time to put the pedal to the metal and find out!",
      "Length: 112 pages",
      "Author: Eric M Esquivel with Shannon Eric Denton",
    ],
    excerpt: "Flynn Friedrich was built for speed. He has never met a race he couldn't win. But there's one thing he isn't fast enough to o ...",
    relatedHeading: "More Title from Actionopolis and Redbear",
    category: "actionopolis",
    ogTitle: "Road Rager - Redbear Publishing",
    ogDescription: "Dark Drivers",
  },
  {
    slug: "test-book",
    title: "Agent of Danger: Strange Polarity",
    subtitle: "Fast paced and Energetic!",
    date: "March 15, 2013",
    formats: ["Ebook", "Kindle Unlimited", "Paperback"],
    purchaseUrl: "https://www.amazon.com/Agent-Danger-Shannon-Eric-Denton-ebook/dp/B00BV6XV9O/ref=sr_1_1?dchild=1&keywords=Jason+Arnett&qid=1596155023&sr=8-1",
    buttonLabel: "Purchase on Amazon",
    image: "redbear-books_0001_Agent_of_Danger_1.jpg",
    width: 563,
    height: 900,
    paragraphs: [
      "Ezekiel Wolfe chased the rumors of a dark organization bent on world domination and it cost him his job as a covert agent. No longer affiliated with any government, he joins three disavowed agents also on the hunt. Alone they had no chance. Together they are mankind's last hope against the otherworldly perils of this ancient evil.",
      "Length: 124 pages",
      "Author: Jason Arnett with Shannon Eric Denton",
    ],
    excerpt: "Ezekiel Wolfe chased the rumors of a dark organization bent on world domination and it cost him his job as a covert agent. No ...",
    relatedHeading: "More Title from Actionopolis and Redbear",
    category: "actionopolis",
    ogTitle: "Agent of Danger: Strange Polarity - Redbear Publishing",
    ogDescription: "Fast paced and Energetic!",
  },
  {
    slug: "all-robots-must-die-nacho-geddon",
    title: "All Robots Must Die: Nacho-Geddon",
    subtitle: "All Robots Must Die!",
    date: "February 24, 2013",
    formats: ["Ebook", "Kindle Unlimited", "Paperback"],
    purchaseUrl: "https://www.amazon.com/All-Robots-Must-Die-Nacho-Geddon-ebook/dp/B00BM7ZOCE/ref=sr_1_1?dchild=1&keywords=Chad+Derdowski+Robotos&qid=1596158317&sr=8-1-spell",
    buttonLabel: "Purchase on Amazon",
    image: "redbear-books_0002_All_Robots_Must_Die.jpg",
    width: 563,
    height: 900,
    paragraphs: [
      "Jake and Elroy wake up to find themselves in a world decimated by warring factions of bizarre creatures. No memories. No backpack. No nachos! (and your best/only friend is a total jerk). They are trapped in a strange land where monkeys with jet packs hate dolphins with cybernetic exoskeletons, dolphins hate intelligent man-apes, sasquatches hate cannibalistic cows, and most everything hates them! However, there is something everyone agrees on and that is...ALL ROBOTS MUST DIE!",
      "Length: 189 Pages",
      "Author: Chad Derdowski with Shannon Eric Denton",
      "\"\"...These high-energy texts and engaging characters will attract reluctant readers as well as fantasy fans.\" - SCHOOL LIBRARY JOURNAL",
    ],
    excerpt: "Jake and Elroy wake up to find themselves in a world decimated by warring factions of bizarre creatures. No memories. No back ...",
    relatedHeading: "More Title from Actionopolis and Redbear",
    category: "actionopolis",
    ogTitle: "All Robots Must Die: Nacho-Geddon - Redbear Publishing",
    ogDescription: "All Robots Must Die!",
  },
  {
    slug: "monstrous",
    title: "Monstrous",
    subtitle: "Blood and Gold",
    date: "February 23, 2013",
    formats: ["Kindle", "Paperback"],
    purchaseUrl: "https://www.amazon.com/Monstrous-Blood-Gold-Justin-Cline-ebook/dp/B00BL5V4YY/ref=sr_1_1?dchild=1&keywords=Monstrous+blood+and+Gold&qid=1596210680&s=books&sr=1-1",
    buttonLabel: "Purchase on Amazon",
    image: "redbear-books_0017_Monstrous.jpg",
    width: 563,
    height: 900,
    paragraphs: [
      "Eric Siders wants nothing more than to escape the confines of the small mining community he calls home but fate has something else in store for him. After stumbling upon a lost cave, he unleashes an ancient evil that has been buried within for more than a century. Now in order to defeat this threat, Eric must become a monster himself. Empowered by an arcane alchemy sealed within the cave, Eric transforms into something monstrous but he must quickly learn to utilize his newfound gifts if he has any hope of surviving the encounter and stopping the creatures that seek to destroy us all!",
      "Length: 135 pages",
      "Author: Justin Cline with Shannon Eric Denton",
    ],
    excerpt: "Eric Siders wants nothing more than to escape the confines of the small mining community he calls home but fate has something ...",
    relatedHeading: "More Title from Actionopolis and Redbear",
    category: "actionopolis",
    ogTitle: "Monstrous - Redbear Publishing",
    ogDescription: "Blood and Gold",
  },
  {
    slug: "me-2",
    title: "Me/2",
    subtitle: "The Chaos Engine",
    date: "February 14, 2013",
    formats: ["Kindle", "Paperback"],
    purchaseUrl: "https://www.amazon.com/Me-Chaos-Engine-Justin-Cline-ebook/dp/B00BGG75IW/ref=sr_1_1?dchild=1&keywords=Me+2+the+chaos+Engine&qid=1596210309&s=books&sr=1-1",
    buttonLabel: "Purchase on Amazon",
    image: "redbear-books_0015_Me-2.jpg",
    width: 563,
    height: 900,
    paragraphs: [
      "Cole Good was your average teenager until a wave of migraine headaches gave him sporadic hyper-intelligence. His submission for the annual science fair, a video game enhancer Cole calls a “chaos engine”, goes haywire and he finds himself pulled into an alternate timeline. Cole is forced to team up with a thrill-seeking adult version of himself as well as Cole’s kid sister who is now older than him! Cole must learn to harness his newfound intelligence in order to survive the upcoming chaos and ensure that all of humanity survives it as well.",
      "Length: 140 pages",
      "Author: Justine Kline with Shannon Eric Denton",
    ],
    excerpt: "Cole Good was your average teenager until a wave of migraine headaches gave him sporadic hyper-intelligence. His submission f ...",
    relatedHeading: "More Title from Actionopolis and Redbear",
    category: "actionopolis",
    ogTitle: "Me/2 - Redbear Publishing",
    ogDescription: "The Chaos Engine",
  },
  {
    slug: "inheritance",
    title: "Inheritance",
    subtitle: "Long Live Zar",
    date: "February 1, 2013",
    formats: ["Kindle", "Paperback"],
    purchaseUrl: "https://www.amazon.com/Inheritance-Long-Live-Scott-Peterson-ebook/dp/B00BEXOLBG/ref=sr_1_fkmr0_1?dchild=1&keywords=Inheritance+Long+Love+zar&qid=1596207240&sr=8-1-fkmr0",
    buttonLabel: "Purchase on Amazon",
    image: "redbear-books_0012_Inheritance.jpg",
    width: 563,
    height: 900,
    paragraphs: [
      "A teenager named Ned must deal with the realization that his father was secretly the world’s greatest hero, the Zar. This realization is short lived when his father is impossibly killed by assassins. Coming to terms with the loss of his father is even harder because Ned’s older brothers think they should have inherited these mighty abilities instead. Now hunted by his father’s killers, regardless of the fact he doesn’t have any idea who they are or how to control the superpowers he’s inherited, Ned must learn quickly or die just like the hero who came before him.",
      "Length: 124 pages",
      "Author: Scott Peterson with Shannon Eric Denton",
      "About the Author: Scott Peterson got his start in comics as an editor on the Batman line of comics, working with the legendary Dennis O’Neil",
    ],
    excerpt: "A teenager named Ned must deal with the realization that his father was secretly the world’s greatest hero, the Zar. This r ...",
    relatedHeading: "More Title from Actionopolis and Redbear",
    category: "actionopolis",
    ogTitle: "Inheritance - Redbear Publishing",
    ogDescription: "Long Live Zar",
  },
  {
    slug: "last-of-the-lycans",
    title: "Last of the Lycans",
    subtitle: "Monarch of the Moon",
    date: "March 10, 2012",
    formats: ["Kindle", "Paperback"],
    purchaseUrl: "https://www.amazon.com/Last-Lycans-Monarch-Tim-Waggoner/dp/1933925396",
    buttonLabel: "Purchase on Amazon",
    image: "redbear-books_0014_Last_of_the_Lycans.jpg",
    width: 563,
    height: 900,
    paragraphs: [
      "A young man must accept his lineage if he is to have any hope of saving mankind from a long forgotten war that may once again encompass us all. Strange events and odd physical changes lead a young man named Marshall to discover that he is actually part werewolf! As he uncovers more about his heritage, Marshall learns that the werewolf race is divided into two camps: those who choose to co-exist peacefully with mankind, and those who hope to feast upon it. When he chooses to side with humanity, Marshall unleashes a centuries-old blood feud that once threatened us all and soon will again!",
      "Length: 106 pages",
      "Author: Tim Waggoner with Shannon Eric Denton",
    ],
    excerpt: "A young man must accept his lineage if he is to have any hope of saving mankind from a long forgotten war that may once again ...",
    relatedHeading: "More Title from Actionopolis and Redbear",
    category: "actionopolis",
    ogTitle: "Last of the Lycans - Redbear Publishing",
    ogDescription: "Monarch of the Moon",
  },
  {
    slug: "knight-star",
    title: "Knight Star",
    subtitle: "Knight of the Starborne",
    date: "December 29, 2011",
    formats: ["Kindle", "Paperback"],
    purchaseUrl: "https://www.amazon.com/Knight-Star-Starborne-Aaron-Rosenberg-ebook/dp/B006RD6TVS/ref=sr_1_1?dchild=1&keywords=knight+star+knight+of+the+starborne&qid=1596207445&sr=8-1",
    buttonLabel: "Purchase on Amazon",
    image: "redbear-books_0013_Knightstar.jpg",
    width: 563,
    height: 900,
    paragraphs: [
      "Marie Bernardin and her father Edgar are stargazing when a meteorite crashes into their campsite and engulfs them in an unearthly energy. Afterward they each discover they have been granted new abilities. But others were tracking the meteorite, others from the same space battle it escaped, and they are determined to retrieve or destroy the gifts it contained—at any cost. Now Marie and Edgar must learn to harness their new powers in time to protect themselves against a threat from beyond the stars. They must become the next KnightStar!",
      "Length: 140 pages",
      "Author: Aaron Rosenberg with Shanon Eric Denton",
    ],
    excerpt: "Marie Bernardin and her father Edgar are stargazing when a meteorite crashes into their campsite and engulfs them in an unear ...",
    relatedHeading: "More Title from Actionopolis and Redbear",
    category: "actionopolis",
    ogTitle: "Knight Star - Redbear Publishing",
    ogDescription: "Knight of the Starborne",
  },
  {
    slug: "megamatrix",
    title: "Megamatrix",
    subtitle: "Hero Within",
    date: "May 8, 2011",
    formats: ["Kindle", "Paperback"],
    purchaseUrl: "https://www.amazon.com/Megamatrix-Hero-Within-Jake-Bell/dp/1933925310",
    buttonLabel: "Purchase on Amazon",
    image: "redbear-books_0016_Megamatrix.jpg",
    width: 563,
    height: 900,
    paragraphs: [
      "In a world robbed of its heroes, a young man inherits the powers of the last great superteam and must decide if he will be its greatest hero... or villain. It’s been years since the last superhero was defeated, and now the super-villains run a world devoid of hope. But before they were lost, the superheroes made a plan. This plan now hinges on Fletcher Bolt, a young man with the power to defeat the evildoers and become humanity’s greatest hero… as long as he doesn’t become it’s most notorious villain!",
      "Length: 136 pages",
      "Author: Jake Bell and Phil Hester with Shanon Eric Denton",
    ],
    excerpt: "In a world robbed of its heroes, a young man inherits the powers of the last great superteam and must decide if he will be it ...",
    relatedHeading: "More Title from Actionopolis and Redbear",
    category: "actionopolis",
    ogTitle: "Megamatrix - Redbear Publishing",
    ogDescription: "Hero Within",
  },
  {
    slug: "evolver-2",
    title: "Evolver",
    subtitle: "Apex Predator",
    date: "November 17, 2010",
    formats: ["Kindle", "Paperback"],
    purchaseUrl: "https://www.amazon.com/Evolver-Predator-Jon-S-Lewis-ebook/dp/B004CYETZC/ref=sr_1_1?dchild=1&keywords=Evolver+Apex+Predtor&qid=1596159321&sr=8-1-spell",
    buttonLabel: "Purchase on Amazon",
    image: "redbear-books_0006_Evolver-1-amazon.jpg",
    width: 563,
    height: 900,
    paragraphs: [
      "Jackson Savage adjusted pretty easily to life in college until his dying father injected him with experimental DNA. Now suspected of terrible crimes, he must adapt quickly to find his father’s murderer. Pursued by a mad scientist’s monsters, Jackson discovers survival skills no other human has.",
      "Length: 105 Pages",
      "Author: Jon S. Lewis, Jason Arnett and Shannon Eric Denton",
    ],
    excerpt: "Jackson Savage adjusted pretty easily to life in college until his dying father injected him with experimental DNA. Now suspe ...",
    relatedHeading: "More Title from Actionopolis and Redbear",
    category: "actionopolis",
    ogTitle: "Evolver - Redbear Publishing",
    ogDescription: "Apex Predator",
  },
  {
    slug: "henrietta-hex-shadows-from-the-past",
    title: "Henrietta Hex: Shadows from the Past",
    subtitle: "A bright, brave young woman, able to speak with ghosts, moves to a small town with a deadly secret. Some spirits are willing to kill to keep those secrets and Henrietta must enlist the aid of the dead if she’s going to save everyone in town from joining the afterlife at once. Length: 66 pages […]",
    date: "July 11, 2010",
    formats: ["Kindle", "Paperback"],
    purchaseUrl: "https://www.amazon.com/Henrietta-Hex-Steven-Philip-Jones-ebook/dp/B003VIWP1A/ref=sr_1_1?dchild=1&keywords=Henrietta+Hex&qid=1596207049&sr=8-1",
    buttonLabel: "Purchase on Amazon",
    image: "Henrietta_Hex.jpg",
    width: 563,
    height: 900,
    paragraphs: [
      "A bright, brave young woman, able to speak with ghosts, moves to a small town with a deadly secret. Some spirits are willing to kill to keep those secrets and Henrietta must enlist the aid of the dead if she’s going to save everyone in town from joining the afterlife at once.",
      "Length: 66 pages",
      "Author: Steven Philip Jones with Shannon Eric Denton",
    ],
    excerpt: "A bright, brave young woman, able to speak with ghosts, moves to a small town with a deadly secret. Some spirits are willing ...",
    relatedHeading: "More Title from Actionopolis and Redbear",
    category: "actionopolis",
    ogTitle: "Henrietta Hex: Shadows from the Past - Redbear Publishing",
    ogDescription: "A bright, brave young woman, able to speak with ghosts, moves to a small town with a deadly secret. Some spirits are willing to kill to keep those secrets and Henrietta must enlist the aid of the dead if she’s going to save everyone in town from joining the afterlife at once. Length: 66 pages […]",
  },
  {
    slug: "astro-aces-the-power-of-three",
    title: "Astro Aces: The Power of Three",
    subtitle: "An Intergalactic School for Budding Superheroes.",
    date: "July 6, 2010",
    formats: ["Kindle"],
    purchaseUrl: "https://www.amazon.com/Astro-Aces-Power-Marsha-Griffin-ebook/dp/B003UYUWU6/ref=sr_1_1?dchild=1&keywords=Astro+Aces+Griffin&qid=1596158912&sr=8-1",
    buttonLabel: "Purchase on Amazon",
    image: "Astro_Aces.jpg",
    width: 563,
    height: 900,
    paragraphs: [
      "On their first day of class at an elite intergalactic school for budding superheroes, three rookie students (one being the first-ever Earthling in attendance) must join forces to survive a surprise attack by a notorious intergalactic criminal. Though they aren’t properly trained, they’ll find that being a hero is something you can’t always learn in school.",
      "Length: 40 pages",
      "Author: Marsha Griffin with Shanon Eric Denton",
    ],
    excerpt: "On their first day of class at an elite intergalactic school for budding superheroes, three rookie students (one being the fi ...",
    relatedHeading: "More Title from Actionopolis and Redbear",
    category: "actionopolis",
    ogTitle: "Astro Aces: The Power of Three - Redbear Publishing",
    ogDescription: "An Intergalactic School for Budding Superheroes.",
  },
  {
    slug: "the-anubis-tapestry-between-twilights",
    title: "The Anubis Tapestry: Between Twilights",
    subtitle: "A Mummy's Curse!",
    date: "September 25, 2006",
    formats: ["Ebook", "Hardcover", "Paperback"],
    purchaseUrl: "https://www.amazon.com/Anubis-Tapestry-Between-Twilights/dp/0974280380/ref=sr_1_1?dchild=1&keywords=BRuce+Zick+Anubis&qid=1596158533&sr=8-1",
    buttonLabel: "Purchase on Amazon",
    image: "Anubis_Tapestry.jpg",
    width: 563,
    height: 900,
    paragraphs: [
      "When a mummy's curse condemns Dr. George Henry’s spirit to the Egyptian Underworld, his son Chance must try to free him. But Chance risks becoming a mummy himself when he binds himself in the wrappings of the mysterious Anubis Tapestry. Led by a comical creature named Blixx, Chance plumbs the depths of the Underworld and encounters a variety of horrible monsters. If Chance can’t return by twilight, he and Blixx will be trapped forever in the dead's domain!",
      "Author: Bruce Zick with Shannon Eric Denton",
    ],
    excerpt: "When a mummy's curse condemns Dr. George Henry’s spirit to the Egyptian Underworld, his son Chance must try to free him. Bu ...",
    relatedHeading: "More Title from Actionopolis and Redbear",
    category: "actionopolis",
    ogTitle: "The Anubis Tapestry: Between Twilights - Redbear Publishing",
    ogDescription: "A Mummy's Curse!",
  },
  {
    slug: "spectrum-0",
    title: "Spectrum #0",
    subtitle: "Comic Issue #0",
    date: "August 3, 2020",
    formats: ["Comic Book"],
    purchaseUrl: "https://the-con-man-store.myshopify.com/collections/50-off-sale-use-code-husitdown-at-check-out/products/spectrum-comic-issue-0",
    buttonLabel: "Purchase",
    image: "Spectrum-0-redbear.jpg",
    width: 593,
    height: 900,
    paragraphs: [
      "If you missed it on Free Comic Book Day, here is the full issue that started it all for Spectrum.",
      "Our planet has been ravaged by two alien attacks and life on Earth is very different. Captain James Raaker is tasked with cleaning it up, but this is just a set-up to destroy everything he loves and quite possibly life on Earth itself!",
      "The four-issue series from Con Man Comics will be written by Tudyk and novelist/producer PJ Haarsma (The Softwire Series) with artwork by Sarah Stone (Transformers) and overseen by Shel Dorf Award-winning editor Shannon Eric Denton",
      "Length: 32 pages",
      "Authors: PJ Haarsma and Alan Tudyk, Illustrations by Sarah Stone",
    ],
    excerpt: "Comic Issue #0",
    relatedHeading: "More Titles from Redbear",
    category: "comics",
    ogTitle: "Spectrum #0 - Redbear Publishing",
    ogDescription: "Comic Issue #0",
  },
  {
    slug: "spectrum-1",
    title: "Spectrum #1",
    subtitle: "Issue #1 (2nd comic in series)",
    date: "August 4, 2020",
    formats: ["Comic Book"],
    purchaseUrl: "",
    buttonLabel: "Purchase",
    image: "Spectrum01_cover.jpg",
    width: 619,
    height: 939,
    paragraphs: [
      "A vicious attack from an invading alien force is unleashed on Earth. The human race suffers catastrophic casualties, but the apocryphal dreams of Captain James Raaker (Nathan Fillion) warn him that the suffering has just begun. Their only hope lies with an untested spaceship built by a madman with his stolen alien technology.",
      "Length: 32 Pages",
      "Authors: PJ Haarsma and Alan Tudyk. Illustrator: Sarah Stone",
    ],
    excerpt: "Issue #1 (2nd comic in series)",
    relatedHeading: "More Titles from Redbear",
    category: "comics",
    ogTitle: "Spectrum #1 - Redbear Publishing",
    ogDescription: "Issue #1 (2nd comic in series)",
  },
  {
    slug: "spectrum-0-alt-cover",
    title: "Spectrum #0 ALT COVER",
    subtitle: "This is an ALT cover to issue #0",
    date: "August 4, 2020",
    formats: ["Comic Book"],
    purchaseUrl: "",
    buttonLabel: "Purchase",
    image: "Spectrum_Comic_Issue-00_Alt-Cover-A.jpg",
    width: 593,
    height: 900,
    paragraphs: [
      "This is a rare ALT cover to the origin story found in issue #0. This comic was first featured on Free Comic Day where over 100,000 copies were sold. Only 1,000 copies of this ALT cover were printed.",
      "Length: 32 pages",
      "Authors: PJ Haarsma and Alan Tudyk. Illustrator: Sarah Stone",
      "Cover Illustrator: Kindra Haugen",
    ],
    excerpt: "This is an ALT cover to issue #0",
    relatedHeading: "More Titles from Redbear",
    category: "comics",
    ogTitle: "Spectrum #0 ALT COVER - Redbear Publishing",
    ogDescription: "This is an ALT cover to issue #0",
  },
  {
    slug: "spectrum-1-alt-cover-a",
    title: "Spectrum #1 ALT COVER A",
    subtitle: "Issue #1 - Alt Cover A by Phil Noto",
    date: "August 4, 2020",
    formats: ["Comic Book"],
    purchaseUrl: "",
    buttonLabel: "Purchase",
    image: "Spectrum_Comic_Issue-01_ALT-A.jpg",
    width: 585,
    height: 900,
    paragraphs: [
      "This is the alternative cover of Spectrum comic issue # 1 featuring the illustrations of famed comic book artist Phil Noto.",
      "Length: 32 pages",
      "Authors: PJ Haarsma and Alan Tudyk. Illustrator: Sarah Stone",
      "Cover Art: Phil Noto",
    ],
    excerpt: "Issue #1 - Alt Cover A by Phil Noto",
    relatedHeading: "More Titles from Redbear",
    category: "comics",
    ogTitle: "Spectrum #1 ALT COVER A - Redbear Publishing",
    ogDescription: "Issue #1 - Alt Cover A by Phil Noto",
  },
  {
    slug: "spectrum-1-alt-cover-b",
    title: "Spectrum #1 ALT COVER B",
    subtitle: "Issue #1 Alt Cover B - Doran",
    date: "August 4, 2020",
    formats: ["Comic Book"],
    purchaseUrl: "",
    buttonLabel: "Purchase",
    image: "Spectrum_Comic_Issue-01_ALT-B.jpg",
    width: 585,
    height: 900,
    paragraphs: [
      "This is the second ALT cover of Spectrum #1 featuring the art of famed comic book artist  Colleen Doran.",
      "Length: 32 pages",
      "Authors: PJ Haarsma and Alan Tudyk. Illustrator: Sarah Stone",
      "Cover Artist: Colleen Doran",
    ],
    excerpt: "Issue #1 Alt Cover B - Doran",
    relatedHeading: "More Titles from Redbear",
    category: "comics",
    ogTitle: "Spectrum #1 ALT COVER B - Redbear Publishing",
    ogDescription: "Issue #1 Alt Cover B - Doran",
  },
  {
    slug: "graveslinger",
    title: "Graveslinger",
    subtitle: "Graphic novel",
    date: "May 20, 2020",
    formats: ["Paperback"],
    purchaseUrl: "https://www.amazon.com/Graveslinger-Shannon-Eric-Denton/dp/1933925604/ref=sr_1_1?dchild=1&keywords=graveslinger+denton&qid=1596421872&sr=8-1",
    buttonLabel: "Purchase on Amazon",
    image: "graveslinger.jpg",
    width: 616,
    height: 900,
    paragraphs: [
      "Accidentally releasing the souls of 117 executed killers from Hell would ruin anybody's day. But for prison undertaker Frank Timmons, that's just the beginning of his troubles. During their first murder spree, the undead killers have slain his beloved Dorothy, and the only way he can save her soul is to track them all down and send them back where they belong! Written by veteran storyteller and artist Shannon Eric Denton (The Revenant) and novelist/comic book writer Jeff Mariotte (Desperadoes), Graveslinger features dynamic art by John Cboins and Nima Sorat.",
      "Length: 140 Pages",
      "Authors: Shannon Eric Denton (Author), Jeff Mariotte (Author), John Cboins (Illustrator), Nima Sorat (Illustrator), Francesco Francavilla (Contributor), Patrick Coyle (Contributor), Kristen Fitzner Denton (Contributor), Ed Dukeshire (Contributor)",
    ],
    excerpt: "Accidentally releasing the souls of 117 executed killers from Hell would ruin anybody's day. But for prison undertaker Frank ...",
    relatedHeading: "More Titles from Komikwerks and Redbear",
    category: "komikwerks",
    ogTitle: "Graveslinger - Redbear Publishing",
    ogDescription: "Graphic novel",
  },
  {
    slug: "big-game",
    title: "Big Game",
    subtitle: "Graphic Novel",
    date: "May 16, 2013",
    formats: ["Paperback"],
    purchaseUrl: "https://www.amazon.com/Big-Game-Shannon-Eric-Denton/dp/0977880966/ref=sr_1_2?dchild=1&keywords=Big+Game+Denton&qid=1596423617&s=books&sr=1-2",
    buttonLabel: "Purchase on Amazon",
    image: "big-game.jpg",
    width: 616,
    height: 900,
    paragraphs: [
      "A Texas ranger is drawn into a supernatural war and bestowed with a thousand-year life span after defeating a demon being pursued by an ancient Chinese warrior. For over one hundred years the gunslinger and the martial artist have hunted the creatures that secretly walk among us. If these two warriors can keep from killing each other, they just may save humanity itself.",
      "Length: 94 pages",
      "Author: Shannon Eric Denton",
    ],
    excerpt: "A Texas ranger is drawn into a supernatural war and bestowed with a thousand-year life span after defeating a demon being pur ...",
    relatedHeading: "More Titles from Komikwerks and Redbear",
    category: "komikwerks",
    ogTitle: "Big Game - Redbear Publishing",
    ogDescription: "Graphic Novel",
  },
  {
    slug: "the-revenant-2",
    title: "The Revenant",
    subtitle: "Graphic novel",
    date: "May 11, 2013",
    formats: ["Paperback"],
    purchaseUrl: "",
    buttonLabel: "Purchase on Amazon",
    image: "The_Revenant.jpg",
    width: 563,
    height: 805,
    paragraphs: [
      "The bad men of Sapphire City have forgotten what it means to be afraid. They’ve risen to power by ruthlessly cutting down all who stand in their way. Now, on the eve of the city's Day of the Dead celebration, one they had long thought dead and buried has returned ...a ghoulish gunslinger called THE REVENANT!",
      "Length: 116 pages",
      "Authors: Rob M. Worley  (Author), Kristen Fitzner Denton (Compiler), Shannon Eric Denton  (Creator), Keith Giffen (Creator), Mateus Santolouco (Illustrator)",
    ],
    excerpt: "The bad men of Sapphire City have forgotten what it means to be afraid. They’ve risen to power by ruthlessly cutting down a ...",
    relatedHeading: "More Titles from Komikwerks and Redbear",
    category: "komikwerks",
    ogTitle: "The Revenant - Redbear Publishing",
    ogDescription: "Graphic novel",
  },
  {
    slug: "roxi-rangers",
    title: "Roxi Rangers",
    subtitle: "Graphic Novel",
    date: "April 27, 2013",
    formats: ["Paperback"],
    purchaseUrl: "https://www.amazon.com/Roxi-Rangers-Kyle-Jolly/dp/0977880915",
    buttonLabel: "Purchase on Amazon",
    image: "roxy-ranger.jpg",
    width: 616,
    height: 900,
    paragraphs: [
      "The Intergalactic Robot-Wars are over. In the aftermath, planetary systems have collapsed and power hungry despots rush to fill the void. A new era of space-pirates, gun-running robots, and corrupt kingdoms has risen up creating the need for those bold enough to protect those who can't protect themselves. Beware despots, villains, and thugs because the Roxi Rangers have arrived!",
      "Length: 64 pages",
      "Authors: Kyle Jolly (Author), Shannon Eric Denton (Author), Travis Moore (Illustrator)",
    ],
    excerpt: "The Intergalactic Robot-Wars are over. In the aftermath, planetary systems have collapsed and power hungry despots rush to fi ...",
    relatedHeading: "More Titles from Komikwerks and Redbear",
    category: "komikwerks",
    ogTitle: "Roxi Rangers - Redbear Publishing",
    ogDescription: "Graphic Novel",
  },
];

export const postsBySlug = Object.fromEntries(posts.map((post) => [post.slug, post]));

export const actionopolisSlugs = [
  "evolver",
  "dragonblood-the-awakening",
  "evolver-2-cell-structure",
  "battery",
  "gargantuan-rise-of-the-behemoths",
  "road-rager",
  "test-book",
  "all-robots-must-die-nacho-geddon",
  "monstrous",
  "me-2",
  "inheritance",
  "last-of-the-lycans",
  "knight-star",
  "megamatrix",
  "evolver-2",
  "henrietta-hex-shadows-from-the-past",
  "astro-aces-the-power-of-three",
  "the-anubis-tapestry-between-twilights",
] as const;

export const spectrumSlugs = [
  "spectrum-0",
  "spectrum-1",
  "spectrum-0-alt-cover",
  "spectrum-1-alt-cover-a",
  "spectrum-1-alt-cover-b",
] as const;

export const komikwerksSlugs = [
  "graveslinger",
  "big-game",
  "the-revenant-2",
  "roxi-rangers",
] as const;

export function getPost(slug: string): Post | undefined {
  return postsBySlug[slug];
}

export function coverAlt(post: Post): string {
  return `${post.title} cover`;
}

export function relatedPosts(post: Post, count = 3): Post[] {
  const pool = posts.filter((item) => item.category === post.category && item.slug !== post.slug);
  return pool.slice(0, count);
}
